server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: redirige todas las rutas al index.html para que React Router las maneje
    location / {
        try_files $uri $uri/ /index.html;
    }
}
